// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[] args) {
		double number = Integer.parseInt(args[0]);
		double counter1 = 0;
		double counter2 = 0;
		while (number > 0) {
			double randomNum = Math.random();
			if (randomNum <= 0.5)
				counter1++;
			else
				counter2++;

			number--;
		}
		if(counter1>counter2)
		number = Math.abs(counter2)/Math.abs(counter1);

		else
		number = Math.abs(counter1)/Math.abs(counter2);

		System.out.println("The ratio is "+  number);

	}
}